"""Download the icons TradeSim uses into trade/assets/icons.js, so the app works
without internet (dash-iconify reads window.IconifyPreload instead of fetching
each icon online). Needs internet once. Run from the trading_simulator folder:

    .\\trade\\venv\\Scripts\\python.exe tools\\fetch_icons.py

Run it again after adding an icon to the code (tests/test_offline.py checks it).
"""
import collections
import glob
import json
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "trade", "assets", "icons.js")

# Icon sets used by the app ("set:name" strings in the code). Add a set here if
# you start using icons from another one.
ICON_SETS = ("carbon", "material-symbols", "mdi", "twemoji")
ICON_NAME = re.compile(r"['\"]((%s):[a-z0-9]+(?:-[a-z0-9]+)*)['\"]" % "|".join(map(re.escape, ICON_SETS)))


def icons_used_in_code():
    """{icon set: {names}} for every "set:name" string in the app's Python files."""
    found = collections.defaultdict(set)
    for path in glob.glob(os.path.join(ROOT, "trade", "**", "*.py"), recursive=True):
        if f"{os.sep}venv{os.sep}" in path:
            continue
        with open(path, encoding="utf-8") as f:
            for full, prefix in ICON_NAME.findall(f.read()):
                found[prefix].add(full.split(":", 1)[1])
    return found


def main():
    sets = []
    for prefix, names in sorted(icons_used_in_code().items()):
        names = sorted(names)
        url = f"https://api.iconify.design/{prefix}.json?icons={','.join(names)}"
        request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (TradeSim icon download)"})
        data = json.loads(urllib.request.urlopen(request, timeout=30).read())
        missing = [n for n in names if n not in data.get("icons", {}) and n not in data.get("aliases", {})]
        if missing:
            raise SystemExit(f"Icons not found in set '{prefix}': {missing}")
        sets.append(data)
        print(f"{prefix}: {len(names)} icons")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Icons used by TradeSim, loaded with the page so they work without internet.\n"
                "// dash-iconify reads window.IconifyPreload before fetching icons online.\n"
                "// Generated by tools/fetch_icons.py: run it again after adding an icon.\n"
                "window.IconifyPreload = " + json.dumps(sets, separators=(",", ":")) + ";\n")
    print(f"Saved {OUT}")


if __name__ == "__main__":
    main()
